"""
Alert Model — Security alerts generated by anomaly detection, policy violations,
credential expirations, and rogue agent behavior.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import String, DateTime, ForeignKey, JSON, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    agent_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("agents.id"), nullable=True, index=True
    )
    alert_type: Mapped[str] = mapped_column(
        String(30), nullable=False, index=True
    )  # anomaly, policy_violation, credential_expiry, rogue_behavior, cascading_failure
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False, index=True
    )  # low, medium, high, critical
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    evidence: Mapped[dict] = mapped_column(JSON, nullable=True)
    owasp_mapping: Mapped[str] = mapped_column(
        String(10), nullable=True
    )  # ASI01–ASI10 mapping
    status: Mapped[str] = mapped_column(
        String(20), default="open", index=True
    )  # open, acknowledged, resolved, dismissed
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True
    )
    resolved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    agent = relationship("Agent", back_populates="alerts")

    def __repr__(self):
        return f"<Alert [{self.severity}] {self.title[:50]}>"
