"""
Q — Alerts API
Management of anomalies and security alerts generated by behavioral monitoring.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import select
from typing import List, Optional

from app.database import get_db
from app.models.alert import Alert
from app.models.agent import Agent
from app.routes.auth import get_current_user
from pydantic import BaseModel
from datetime import datetime, timezone

router = APIRouter(prefix="/alerts", tags=["Alerts"])

class AlertResponse(BaseModel):
    id: str
    agent_id: str
    alert_type: str
    severity: str
    message: str
    status: str
    created_at: datetime
    
    class Config:
        from_attributes = True

class AlertStatusUpdate(BaseModel):
    status: str  # open, investigating, resolved, false_positive

@router.get("/", response_model=List[AlertResponse])
def get_alerts(
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Get all alerts for agents owned by the current user."""
    # Find user's agents
    agents = db.execute(select(Agent.id).where(Agent.owner_id == current_user.id)).scalars().all()
    if not agents:
        return []
        
    alerts = db.execute(
        select(Alert).where(Alert.agent_id.in_(agents)).order_by(Alert.created_at.desc())
    ).scalars().all()
    
    return alerts

@router.put("/{alert_id}/status")
def update_alert_status(
    alert_id: str,
    update_data: AlertStatusUpdate,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Update the status of an alert (e.g. mark resolved)."""
    alert = db.execute(select(Alert).where(Alert.id == alert_id)).scalars().first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
        
    # Verify ownership
    agent = db.execute(select(Agent).where(Agent.id == alert.agent_id)).scalars().first()
    if not agent or agent.owner_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")
        
    valid_statuses = ["open", "investigating", "resolved", "false_positive"]
    if update_data.status not in valid_statuses:
        raise HTTPException(status_code=400, detail="Invalid status")
        
    alert.status = update_data.status
    if update_data.status in ["resolved", "false_positive"]:
        alert.resolved_at = datetime.now(timezone.utc)
        
    db.commit()
    return {"message": "Status updated"}
